apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m8asosozu-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-46d1258505.z5uy.p3.openshiftapps.com/rhtap/rhtap-qe:30fac378bf258731a9f51bae81cee306bb9146f5@sha256:e504f6895a4c5f0777f81882029f4cc979e7057887af1881d96273aaf80ee937
          name: container-image
